import Mathlib

namespace NSRightAngleRealityMirror

noncomputable section

structure C3 where
  x : ℂ
  y : ℂ
  z : ℂ
  deriving DecidableEq

/-- Bilinear Fourier dot product, with no complex conjugation. -/
def dot (u r : C3) : ℂ :=
  u.x * r.x + u.y * r.y + u.z * r.z

/-- The symmetrized pre-Leray quadratic source generated by two Fourier legs. -/
def source (r s u v : C3) : C3 :=
  ⟨dot u s * v.x + dot v r * u.x,
   dot u s * v.y + dot v r * u.y,
   dot u s * v.z + dot v r * u.z⟩

/-- Leray projection at the sum frequency `(1,1,0)`. -/
def projectSum (w : C3) : C3 :=
  ⟨(w.x - w.y) / 2, (w.y - w.x) / 2, w.z⟩

/-- Leray projection at the reality-mirror frequency `(-1,1,0)`. -/
def projectMirror (w : C3) : C3 :=
  ⟨(w.x + w.y) / 2, (w.x + w.y) / 2, w.z⟩

/-- Right-angle unit carriers. -/
def p : C3 := ⟨0, 1, 0⟩
def q : C3 := ⟨1, 0, 0⟩
def negQ : C3 := ⟨-1, 0, 0⟩

/-- Scaled helical polarizations: negative helicity at `p`, positive helicity
at `q`, and the real-field conjugate at `-q`.  The omitted common factor
`1/sqrt 2` multiplies every source by the same nonzero scalar. -/
def a : C3 := ⟨-1, 0, -Complex.I⟩
def b : C3 := ⟨0, 1, Complex.I⟩
def bConj : C3 := ⟨0, 1, -Complex.I⟩

/-- The common transverse source vector. -/
def verticalSource : C3 := ⟨0, 0, -2 * Complex.I⟩

/-- Exact desired sum-channel source after Leray projection. -/
theorem desired_source_exact :
    projectSum (source p q a b) = verticalSource := by
  ext <;>
    norm_num [projectSum, source, dot, p, q, a, b, verticalSource] <;>
    ring_nf

/-- Exact reality-mirror difference-channel source after Leray projection. -/
theorem mirror_source_exact :
    projectMirror (source p negQ a bConj) = verticalSource := by
  ext <;>
    norm_num [projectMirror, source, dot, p, negQ, a, bConj,
      verticalSource] <;>
    ring_nf

/-- The desired and mirror channels are born with exactly the same projected
vector source. -/
theorem desired_equals_reality_mirror :
    projectSum (source p q a b) =
      projectMirror (source p negQ a bConj) := by
  rw [desired_source_exact, mirror_source_exact]

/-- The common source is nonzero. -/
theorem verticalSource_ne_zero : verticalSource ≠ 0 := by
  intro h
  have hz := congrArg C3.z h
  have hprod : (-2 : ℂ) * Complex.I = 0 := by
    simpa [verticalSource] using hz
  rcases mul_eq_zero.mp hprod with htwo | hI
  · norm_num at htwo
  · exact Complex.I_ne_zero hI

/-- Unnormalized probes for the two helicities at the sum frequency. -/
def plusProbe (r : ℂ) (w : C3) : ℂ :=
  w.x - w.y - Complex.I * r * w.z

def minusProbe (r : ℂ) (w : C3) : ℂ :=
  w.x - w.y + Complex.I * r * w.z

/-- A purely normal source has opposite coefficients in the two child
helicities, hence equal coefficient magnitude. -/
theorem child_helicity_probes_opposite (r : ℂ) :
    plusProbe r verticalSource = -minusProbe r verticalSource := by
  simp [plusProbe, minusProbe, verticalSource]
  ring

/-- Exact equality of the two child-helicity coefficient norms. -/
theorem child_helicity_norms_equal (r : ℂ) :
    ‖plusProbe r verticalSource‖ = ‖minusProbe r verticalSource‖ := by
  calc
    ‖plusProbe r verticalSource‖ = ‖-minusProbe r verticalSource‖ := by
      rw [child_helicity_probes_opposite]
    _ = ‖minusProbe r verticalSource‖ := norm_neg _

end

end NSRightAngleRealityMirror
