import Mathlib

namespace NSRightAngleRealityMirror

abbrev C3 := Fin 3 → ℂ

/-- Bilinear Fourier dot product, with no complex conjugation. -/
def dot (u r : C3) : ℂ :=
  u 0 * r 0 + u 1 * r 1 + u 2 * r 2

/-- The symmetrized pre-Leray quadratic source generated by two Fourier legs. -/
def source (r s u v : C3) : C3 := fun j =>
  dot u s * v j + dot v r * u j

/-- Leray projection at the sum frequency `(1,1,0)`. -/
def projectSum (w : C3) : C3 :=
  ![(w 0 - w 1) / 2, (w 1 - w 0) / 2, w 2]

/-- Leray projection at the reality-mirror frequency `(-1,1,0)`. -/
def projectMirror (w : C3) : C3 :=
  ![(w 0 + w 1) / 2, (w 0 + w 1) / 2, w 2]

/-- Right-angle unit carriers. -/
def p : C3 := ![0, 1, 0]
def q : C3 := ![1, 0, 0]
def negQ : C3 := ![-1, 0, 0]

/-- Scaled helical polarizations: negative helicity at `p`, positive helicity
at `q`, and the real-field conjugate at `-q`.  The omitted common factor
`1/sqrt 2` multiplies every source by the same nonzero scalar. -/
def a : C3 := ![-1, 0, -Complex.I]
def b : C3 := ![0, 1, Complex.I]
def bConj : C3 := ![0, 1, -Complex.I]

/-- The common transverse source vector. -/
def verticalSource : C3 := ![0, 0, -2 * Complex.I]

/-- Exact desired sum-channel source after Leray projection. -/
theorem desired_source_exact :
    projectSum (source p q a b) = verticalSource := by
  funext j
  fin_cases j <;>
    norm_num [projectSum, source, dot, p, q, a, b, verticalSource] <;>
    ring

/-- Exact reality-mirror difference-channel source after Leray projection. -/
theorem mirror_source_exact :
    projectMirror (source p negQ a bConj) = verticalSource := by
  funext j
  fin_cases j <;>
    norm_num [projectMirror, source, dot, p, negQ, a, bConj,
      verticalSource] <;>
    ring

/-- The desired and mirror channels are born with exactly the same projected
vector source. -/
theorem desired_equals_reality_mirror :
    projectSum (source p q a b) =
      projectMirror (source p negQ a bConj) := by
  rw [desired_source_exact, mirror_source_exact]

/-- The common source is nonzero. -/
theorem verticalSource_ne_zero : verticalSource ≠ 0 := by
  intro h
  have hz := congrFun h (2 : Fin 3)
  norm_num [verticalSource] at hz

/-- Unnormalized probes for the two helicities at the sum frequency. -/
def plusProbe (r : ℂ) (w : C3) : ℂ :=
  w 0 - w 1 - Complex.I * r * w 2

def minusProbe (r : ℂ) (w : C3) : ℂ :=
  w 0 - w 1 + Complex.I * r * w 2

/-- A purely normal source has opposite coefficients in the two child
helicities, hence equal coefficient magnitude. -/
theorem child_helicity_probes_opposite (r : ℂ) :
    plusProbe r verticalSource = -minusProbe r verticalSource := by
  simp [plusProbe, minusProbe, verticalSource]
  ring

/-- Exact equality of the two child-helicity coefficient norms. -/
theorem child_helicity_norms_equal (r : ℂ) :
    ‖plusProbe r verticalSource‖ = ‖minusProbe r verticalSource‖ := by
  rw [child_helicity_probes_opposite]
  simp

end NSRightAngleRealityMirror
