import HodgeThomasRelationCore

#print axioms HodgeThomasRelationCore.exists_detected_relation_iff_not_le_kernel
#print axioms HodgeThomasRelationCore.no_detected_relation_of_injective
#print axioms HodgeThomasRelationCore.detected_relation_strictly_shrinks_kernel
#print axioms HodgeThomasRelationCore.cocycle_is_coboundary_of_central_scalar
#print axioms HodgeThomasRelationCore.cocycle_is_coboundary_of_central_negation
#print axioms HodgeThomasRelationCore.IsotropicCollisionObstruction.relation_normal_form
#print axioms HodgeThomasRelationCore.IsotropicCollisionObstruction.nonzero_relation_uses_all_three
#print axioms HodgeThomasRelationCore.IsotropicCollisionObstruction.required_pairings_nonzero
#print axioms HodgeThomasRelationCore.IsotropicCollisionObstruction.nonzero_relation_forces_nonorthogonal_support
