import Mathlib

/-!
# RH iterated-log witness-window localization: finite scalar core

Honesty status: this file formalizes only the real-algebra budget used after the
analytic Fourier-tail and global-envelope estimates have already been supplied.
It does not define the Riemann zeta function, the Weil distribution, the
triangular box family, infinite convolutions, Fourier transforms, or RH.  A
clean build therefore verifies only the displayed finite scalar implications.
-/

namespace MillenniumBraid
namespace RHIteratedLogWindowFinite

/--
If the exterior bad mass costs at most `eta / 4`, then an interior floor
`-eta / 2` and the exterior floor `-B` force the total lower estimate to be at
least `-3*eta/4`.
-/
theorem twoRegionLowerBound
    (eta B t : ℝ)
    (heta : 0 ≤ eta)
    (ht : 0 ≤ t)
    (hbudget : B * t ≤ eta / 4) :
    -(eta / 2) * (1 - t) - B * t ≥ -(3 * eta / 4) := by
  nlinarith

/--
An average known to be at most `-eta` cannot simultaneously obey the lower
estimate generated by an interior `-eta/2` floor and an exterior tail budget
`B*t ≤ eta/4`.
-/
theorem negativeAverageContradiction
    (eta B t avg : ℝ)
    (heta : 0 < eta)
    (ht : 0 ≤ t)
    (hbudget : B * t ≤ eta / 4)
    (havg : avg ≤ -eta)
    (hlower : -(eta / 2) * (1 - t) - B * t ≤ avg) :
    False := by
  have hfloor := twoRegionLowerBound eta B t (le_of_lt heta) ht hbudget
  nlinarith

/--
Contrapositive form: under a genuinely negative average, the putative
interior-floor lower estimate must fail.
-/
theorem negativeAverageForcesInteriorFloorFailure
    (eta B t avg : ℝ)
    (heta : 0 < eta)
    (ht : 0 ≤ t)
    (hbudget : B * t ≤ eta / 4)
    (havg : avg ≤ -eta) :
    ¬ (-(eta / 2) * (1 - t) - B * t ≤ avg) := by
  intro hlower
  exact negativeAverageContradiction eta B t avg heta ht hbudget havg hlower

/--
The exact endpoint arithmetic used in the proof: the interior half-budget and
exterior quarter-budget leave a strict quarter-gap to an average at `-eta`.
-/
theorem localizationGap (eta : ℝ) (heta : 0 < eta) :
    -(3 * eta / 4) > -eta := by
  linarith

#print axioms twoRegionLowerBound
#print axioms negativeAverageContradiction
#print axioms negativeAverageForcesInteriorFloorFailure
#print axioms localizationGap

end RHIteratedLogWindowFinite
end MillenniumBraid
