import Mathlib

/-!
# RH theta-iteration cocycle finite core

HONESTY BOUNDARY

This file formalizes only an abstract finite recurrence used by the paper-level
Chebyshev self-map identity:

* a state-dependent recurrence with nonnegative toll gives one-step descent;
* negativity persists under the state map;
* the recurrence telescopes over every finite orbit;
* a fixed point has zero toll;
* an exact fixed negative countermodel shows that the cocycle alone does not
  imply positivity.

It does not formalize primes, the Chebyshev theta function, real integrals,
Johnston's criterion, zeta zeros, RH, or any official Clay statement.
-/

namespace MillenniumBraid
namespace RHThetaIterationCocycleFinite

/-- The forward orbit generated by one state map. -/
def orbit {X : Type*} (T : X → X) (x : X) : ℕ → X
  | 0 => x
  | n + 1 => T (orbit T x n)

@[simp]
theorem orbit_zero {X : Type*} (T : X → X) (x : X) :
    orbit T x 0 = x := rfl

@[simp]
theorem orbit_succ {X : Type*} (T : X → X) (x : X) (n : ℕ) :
    orbit T x (n + 1) = T (orbit T x n) := rfl

variable {X : Type*}
variable (T : X → X) (P Q C : X → ℝ)

/-- An exact recurrence with nonnegative toll makes `P` nonincreasing along
one application of the state map. -/
theorem one_step_descent
    (hrec : ∀ x, P x = P (T x) + Q (T x) + C x)
    (hQ : ∀ x, 0 ≤ Q x)
    (hC : ∀ x, 0 ≤ C x)
    (x : X) :
    P (T x) ≤ P x := by
  have h := hrec x
  linarith [hQ (T x), hC x]

/-- Once the state is negative, every next state is negative as well. -/
theorem negative_persists_one_step
    (hrec : ∀ x, P x = P (T x) + Q (T x) + C x)
    (hQ : ∀ x, 0 ≤ Q x)
    (hC : ∀ x, 0 ≤ C x)
    {x : X}
    (hx : P x < 0) :
    P (T x) < 0 := by
  exact lt_of_le_of_lt (one_step_descent T P Q C hrec hQ hC x) hx

/-- Negativity persists along every finite orbit. -/
theorem negative_persists_along_orbit
    (hrec : ∀ x, P x = P (T x) + Q (T x) + C x)
    (hQ : ∀ x, 0 ≤ Q x)
    (hC : ∀ x, 0 ≤ C x)
    {x : X}
    (hx : P x < 0) :
    ∀ n : ℕ, P (orbit T x n) < 0 := by
  intro n
  induction n with
  | zero => simpa using hx
  | succ n ih =>
      simpa using negative_persists_one_step T P Q C hrec hQ hC ih

/-- Exact finite telescope for the state-dependent toll recurrence. -/
theorem finite_telescope
    (hrec : ∀ x, P x = P (T x) + Q (T x) + C x)
    (x : X) :
    ∀ n : ℕ,
      P x =
        P (orbit T x n) +
          ∑ j ∈ Finset.range n,
            (Q (orbit T x (j + 1)) + C (orbit T x j)) := by
  intro n
  induction n with
  | zero => simp
  | succ n ih =>
      rw [Finset.sum_range_succ]
      calc
        P x =
            P (orbit T x n) +
              ∑ j ∈ Finset.range n,
                (Q (orbit T x (j + 1)) + C (orbit T x j)) := ih
        _ =
            (P (T (orbit T x n)) + Q (T (orbit T x n)) +
                C (orbit T x n)) +
              ∑ j ∈ Finset.range n,
                (Q (orbit T x (j + 1)) + C (orbit T x j)) := by
              rw [hrec (orbit T x n)]
        _ =
            P (orbit T x (n + 1)) +
              (∑ j ∈ Finset.range n,
                (Q (orbit T x (j + 1)) + C (orbit T x j)) +
                (Q (orbit T x (n + 1)) + C (orbit T x n))) := by
              simp only [orbit_succ]
              ring

/-- At a fixed point, an exact nonnegative toll must vanish. The theorem does
not impose any sign on `P` itself. -/
theorem fixed_point_has_zero_toll
    (hrec : ∀ x, P x = P (T x) + Q (T x) + C x)
    (hQ : ∀ x, 0 ≤ Q x)
    (hC : ∀ x, 0 ≤ C x)
    {x : X}
    (hfix : T x = x) :
    Q x = 0 ∧ C x = 0 := by
  have hsum : Q x + C x = 0 := by
    have h := hrec x
    rw [hfix] at h
    linarith
  constructor <;> linarith [hQ x, hC x]

/-- Smallest exact countermodel: identity state map, negative potential, and
zero toll satisfy the whole recurrence. -/
def counterT : Unit → Unit := id

def counterP : Unit → ℝ := fun _ => -1

def counterQ : Unit → ℝ := fun _ => 0

def counterC : Unit → ℝ := fun _ => 0

/-- The abstract cocycle and nonnegative toll do not force positivity. -/
theorem fixed_negative_countermodel :
    (∀ x,
      counterP x =
        counterP (counterT x) + counterQ (counterT x) + counterC x) ∧
      (∀ x, 0 ≤ counterQ x) ∧
      (∀ x, 0 ≤ counterC x) ∧
      counterT () = () ∧
      counterP () < 0 := by
  constructor
  · intro x
    cases x
    norm_num [counterP, counterQ, counterC, counterT]
  constructor
  · intro x
    cases x
    norm_num [counterQ]
  constructor
  · intro x
    cases x
    norm_num [counterC]
  constructor
  · rfl
  · norm_num [counterP]

#print axioms orbit_zero
#print axioms orbit_succ
#print axioms one_step_descent
#print axioms negative_persists_one_step
#print axioms negative_persists_along_orbit
#print axioms finite_telescope
#print axioms fixed_point_has_zero_toll
#print axioms fixed_negative_countermodel

end RHThetaIterationCocycleFinite
end MillenniumBraid
