import Mathlib

/-!
# Navier--Stokes: Farkas obstruction to the current nine-carrier Beltrami cone

The equal-shell carriers in `Millennium/NavierStokes/NinePolarizationCarrierDesign.lean`
are individually transverse to the assigned rank-one polarizations.  A real
same-helicity Beltrami block at carrier `k`, however, has phase-averaged stress
proportional to the transverse projector

`I - kHat tensor kHat`.

For the current carriers, `|k|^2 = 17`; after multiplying by `17`, the relevant
stress generator is `Q_k = 17 I - k tensor k`.  This file gives an exact Farkas
certificate showing that the positive cone generated by the nine `Q_k` does not
contain `17 I`.

This is finite linear algebra.  It does not rule out a redesigned carrier set,
non-Beltrami blocks, mixed helicities, or a different analytic construction.
It is not a proof or disproof of Navier--Stokes regularity.
-/

namespace Millennium.NavierStokes.BeltramiCarrierConeObstruction

abbrev V3Z := Fin 3 → ℤ
abbrev Sym6Z := Fin 6 → ℤ

/-- The current nine equal-shell integer carriers. -/
def carrier : Fin 9 → V3Z := ![
  ![0, 4, 1],
  ![4, 0, 1],
  ![4, 1, 0],
  ![2, -2, 3],
  ![2, 2, 3],
  ![2, 3, -2],
  ![2, 3, 2],
  ![3, 2, -2],
  ![3, 2, 2]
]

/-- Symmetric matrices are stored in the coordinate order
`(xx, yy, zz, xy, xz, yz)`. -/
def projectorStress (k : V3Z) : Sym6Z := ![
  17 - k 0 ^ 2,
  17 - k 1 ^ 2,
  17 - k 2 ^ 2,
  -(k 0 * k 1),
  -(k 0 * k 2),
  -(k 1 * k 2)
]

/-- The exact projector stresses `17 I - k tensor k`. -/
def qStress : Fin 9 → Sym6Z := ![
  ![17, 1, 16, 0, 0, -4],
  ![1, 17, 16, 0, -4, 0],
  ![1, 16, 17, -4, 0, 0],
  ![13, 13, 8, 4, -6, 6],
  ![13, 13, 8, -4, -6, -6],
  ![13, 8, 13, -6, 4, 6],
  ![13, 8, 13, -6, -4, -6],
  ![8, 13, 13, -6, 6, 4],
  ![8, 13, 13, -6, -6, -4]
]

/-- The table above is exactly the projector formula for every carrier. -/
theorem qStress_eq_projectorStress (i : Fin 9) :
    qStress i = projectorStress (carrier i) := by
  fin_cases i <;> ext j <;> fin_cases j <;>
    norm_num [qStress, projectorStress, carrier]

/-- The separating linear functional
`L(M) = -6 Mzz - 183 Mxy - 154 Mxz - 24 Myz`. -/
def separator (m : Sym6Z) : ℤ :=
  -6 * m 2 - 183 * m 3 - 154 * m 4 - 24 * m 5

/-- Exact values of the separator on the nine projector generators. -/
def separatorValue : Fin 9 → ℤ :=
  ![0, 520, 630, 0, 1752, 260, 1780, 0, 2040]

/-- The separator is nonnegative on every current projector generator. -/
theorem separator_exact (i : Fin 9) :
    separator (qStress i) = separatorValue i := by
  fin_cases i <;> norm_num [separator, qStress, separatorValue]

theorem separator_nonneg (i : Fin 9) :
    0 ≤ separator (qStress i) := by
  rw [separator_exact]
  fin_cases i <;> norm_num [separatorValue]

/-- The target isotropic stress is strictly separated from the cone. -/
def target17I : Sym6Z := ![17, 17, 17, 0, 0, 0]

theorem separator_target17I : separator target17I = -102 := by
  norm_num [separator, target17I]

/-- Explicit coordinates of a nonnegative linear combination of the nine
projector stresses. -/
def coneCoordinates (a : Fin 9 → ℝ) : Fin 6 → ℝ := ![
  17*a 0 + a 1 + a 2 + 13*a 3 + 13*a 4 + 13*a 5 + 13*a 6 + 8*a 7 + 8*a 8,
  a 0 + 17*a 1 + 16*a 2 + 13*a 3 + 13*a 4 + 8*a 5 + 8*a 6 + 13*a 7 + 13*a 8,
  16*a 0 + 16*a 1 + 17*a 2 + 8*a 3 + 8*a 4 + 13*a 5 + 13*a 6 + 13*a 7 + 13*a 8,
  -4*a 2 + 4*a 3 - 4*a 4 - 6*a 5 - 6*a 6 - 6*a 7 - 6*a 8,
  -4*a 1 - 6*a 3 - 6*a 4 + 4*a 5 - 4*a 6 + 6*a 7 - 6*a 8,
  -4*a 0 + 6*a 3 - 6*a 4 + 6*a 5 - 6*a 6 + 4*a 7 - 4*a 8
]

/-- The exact dual identity behind the Farkas certificate. -/
theorem cone_separator_identity (a : Fin 9 → ℝ) :
    -6 * coneCoordinates a 2
      - 183 * coneCoordinates a 3
      - 154 * coneCoordinates a 4
      - 24 * coneCoordinates a 5
      = 520*a 1 + 630*a 2 + 1752*a 4 + 260*a 5 + 1780*a 6 + 2040*a 8 := by
  simp [coneCoordinates]
  ring

/-- Every nonnegative combination of the nine current projector stresses lies
on the nonnegative side of the separator. -/
theorem cone_separator_nonneg
    (a : Fin 9 → ℝ) (ha : ∀ i, 0 ≤ a i) :
    0 ≤ -6 * coneCoordinates a 2
      - 183 * coneCoordinates a 3
      - 154 * coneCoordinates a 4
      - 24 * coneCoordinates a 5 := by
  rw [cone_separator_identity]
  have h1 := ha 1
  have h2 := ha 2
  have h4 := ha 4
  have h5 := ha 5
  have h6 := ha 6
  have h8 := ha 8
  positivity

/-- There are no nonnegative amplitudes whose Beltrami projector stresses sum
to `17 I`.  Thus the identity is outside the positive cone of the current
nine-carrier family. -/
theorem no_nonnegative_identity_decomposition :
    ¬ ∃ a : Fin 9 → ℝ,
      (∀ i, 0 ≤ a i) ∧
      (∀ j, coneCoordinates a j = (target17I j : ℝ)) := by
  rintro ⟨a, ha, hcoord⟩
  have hnonneg := cone_separator_nonneg a ha
  have htarget :
      -6 * coneCoordinates a 2
        - 183 * coneCoordinates a 3
        - 154 * coneCoordinates a 4
        - 24 * coneCoordinates a 5 = -102 := by
    rw [hcoord 2, hcoord 3, hcoord 4, hcoord 5]
    norm_num [target17I]
  linarith

#print axioms qStress_eq_projectorStress
#print axioms separator_exact
#print axioms separator_nonneg
#print axioms separator_target17I
#print axioms cone_separator_identity
#print axioms cone_separator_nonneg
#print axioms no_nonnegative_identity_decomposition

end Millennium.NavierStokes.BeltramiCarrierConeObstruction
