import Mathlib

/-!
# Navier--Stokes: explicit nine-direction positive stress cone

This file closes the finite matrix-algebra gate behind a microcell Reynolds-stress
construction.  Every real symmetric `3 x 3` matrix `S` can be shifted by a
sufficiently large scalar matrix `lambda I` and represented exactly as a positive
combination of nine fixed rank-one matrices:

* the three coordinate axes;
* the plus/minus directions for each coordinate pair.

The isotropic shift is the pressure-gauge direction in incompressible flow.

The file proves only finite matrix algebra and coefficient positivity.  It does
not construct localized divergence-free packets, prove a homogenization estimate,
control cross-cell interactions, solve Navier--Stokes, or produce blow-up.
-/

namespace Millennium.NavierStokes.NineDirectionStressCone

open Matrix

abbrev V3 := Fin 3 → ℝ
abbrev M3 := Matrix (Fin 3) (Fin 3) ℝ

/-- Rank-one symmetric matrix generated by a vector. -/
def outer (v : V3) : M3 := fun i j => v i * v j

/-- Coordinate directions. -/
def e0 : V3 := ![1, 0, 0]
def e1 : V3 := ![0, 1, 0]
def e2 : V3 := ![0, 0, 1]

/-- Pair directions for the `01`, `02`, and `12` planes. -/
def p01 : V3 := ![1, 1, 0]
def m01 : V3 := ![1, -1, 0]
def p02 : V3 := ![1, 0, 1]
def m02 : V3 := ![1, 0, -1]
def p12 : V3 := ![0, 1, 1]
def m12 : V3 := ![0, 1, -1]

/-- A symmetric matrix written by its six independent entries. -/
def symmetricMatrix
    (s00 s11 s22 s01 s02 s12 : ℝ) : M3 :=
  ![![s00, s01, s02],
    ![s01, s11, s12],
    ![s02, s12, s22]]

/-- The pressure-gauge shifted target `lambda I + S`. -/
def shiftedTarget
    (lambda s00 s11 s22 s01 s02 s12 : ℝ) : M3 :=
  ![![lambda + s00, s01, s02],
    ![s01, lambda + s11, s12],
    ![s02, s12, lambda + s22]]

/-- The nine nonnegative coefficient slots. -/
def a0 (lambda s00 r01 r02 : ℝ) : ℝ := lambda + s00 - r01 - r02
def a1 (lambda s11 r01 r12 : ℝ) : ℝ := lambda + s11 - r01 - r12
def a2 (lambda s22 r02 r12 : ℝ) : ℝ := lambda + s22 - r02 - r12

def a01p (r01 s01 : ℝ) : ℝ := (r01 + s01) / 2
def a01m (r01 s01 : ℝ) : ℝ := (r01 - s01) / 2
def a02p (r02 s02 : ℝ) : ℝ := (r02 + s02) / 2
def a02m (r02 s02 : ℝ) : ℝ := (r02 - s02) / 2
def a12p (r12 s12 : ℝ) : ℝ := (r12 + s12) / 2
def a12m (r12 s12 : ℝ) : ℝ := (r12 - s12) / 2

/-- Explicit nine-direction synthesized stress. -/
def synthesizedStress
    (lambda s00 s11 s22 s01 s02 s12 r01 r02 r12 : ℝ) : M3 :=
  a0 lambda s00 r01 r02 • outer e0 +
  a1 lambda s11 r01 r12 • outer e1 +
  a2 lambda s22 r02 r12 • outer e2 +
  a01p r01 s01 • outer p01 +
  a01m r01 s01 • outer m01 +
  a02p r02 s02 • outer p02 +
  a02m r02 s02 • outer m02 +
  a12p r12 s12 • outer p12 +
  a12m r12 s12 • outer m12

/-- Exact entrywise reconstruction of `lambda I + S`. -/
theorem synthesizedStress_eq_shiftedTarget
    (lambda s00 s11 s22 s01 s02 s12 r01 r02 r12 : ℝ) :
    synthesizedStress lambda s00 s11 s22 s01 s02 s12 r01 r02 r12 =
      shiftedTarget lambda s00 s11 s22 s01 s02 s12 := by
  ext i j
  fin_cases i <;> fin_cases j <;>
    simp [synthesizedStress, shiftedTarget, outer,
      e0, e1, e2, p01, m01, p02, m02, p12, m12,
      a0, a1, a2, a01p, a01m, a02p, a02m, a12p, a12m] <;>
    ring

/-- Strict pair margins make all six oblique-direction weights positive. -/
theorem pairWeights_positive
    {r01 r02 r12 s01 s02 s12 : ℝ}
    (h01 : |s01| < r01)
    (h02 : |s02| < r02)
    (h12 : |s12| < r12) :
    0 < a01p r01 s01 ∧ 0 < a01m r01 s01 ∧
    0 < a02p r02 s02 ∧ 0 < a02m r02 s02 ∧
    0 < a12p r12 s12 ∧ 0 < a12m r12 s12 := by
  have h01' := abs_lt.mp h01
  have h02' := abs_lt.mp h02
  have h12' := abs_lt.mp h12
  unfold a01p a01m a02p a02m a12p a12m
  constructor
  · linarith
  constructor
  · linarith
  constructor
  · linarith
  constructor
  · linarith
  constructor <;> linarith

/-- A sufficiently large pressure shift makes all three axis weights positive. -/
theorem axisWeights_positive
    {lambda s00 s11 s22 r01 r02 r12 : ℝ}
    (h0 : -s00 + r01 + r02 < lambda)
    (h1 : -s11 + r01 + r12 < lambda)
    (h2 : -s22 + r02 + r12 < lambda) :
    0 < a0 lambda s00 r01 r02 ∧
    0 < a1 lambda s11 r01 r12 ∧
    0 < a2 lambda s22 r02 r12 := by
  unfold a0 a1 a2
  constructor
  · linarith
  constructor <;> linarith

/-- Full positive-cone certificate: all nine coefficients are strictly positive
and the resulting rank-one sum equals the pressure-shifted target. -/
theorem positive_nine_direction_certificate
    {lambda s00 s11 s22 s01 s02 s12 r01 r02 r12 : ℝ}
    (h01 : |s01| < r01)
    (h02 : |s02| < r02)
    (h12 : |s12| < r12)
    (h0 : -s00 + r01 + r02 < lambda)
    (h1 : -s11 + r01 + r12 < lambda)
    (h2 : -s22 + r02 + r12 < lambda) :
    (0 < a0 lambda s00 r01 r02 ∧
     0 < a1 lambda s11 r01 r12 ∧
     0 < a2 lambda s22 r02 r12 ∧
     0 < a01p r01 s01 ∧ 0 < a01m r01 s01 ∧
     0 < a02p r02 s02 ∧ 0 < a02m r02 s02 ∧
     0 < a12p r12 s12 ∧ 0 < a12m r12 s12) ∧
    synthesizedStress lambda s00 s11 s22 s01 s02 s12 r01 r02 r12 =
      shiftedTarget lambda s00 s11 s22 s01 s02 s12 := by
  have haxis := axisWeights_positive h0 h1 h2
  have hpairs := pairWeights_positive h01 h02 h12
  constructor
  · rcases haxis with ⟨ha0, ha1, ha2⟩
    rcases hpairs with ⟨h01p, h01m, h02p, h02m, h12p, h12m⟩
    exact ⟨ha0, ha1, ha2, h01p, h01m, h02p, h02m, h12p, h12m⟩
  · exact synthesizedStress_eq_shiftedTarget
      lambda s00 s11 s22 s01 s02 s12 r01 r02 r12

#print axioms synthesizedStress_eq_shiftedTarget
#print axioms pairWeights_positive
#print axioms axisWeights_positive
#print axioms positive_nine_direction_certificate

end Millennium.NavierStokes.NineDirectionStressCone
