import Mathlib

/-!
# Hodge C428: odd-cohomology parity firewall

This file formalizes the finite support arithmetic behind the theorem that a
tensor category generated by projective K3 cohomology and integer Tate twists
cannot contain the full cohomology of a variety with nonzero odd cohomology.

A projective K3 surface has Betti degrees `0, 2, 4`. Tensor products add
cohomological degrees, integer Tate twists shift them by an even number, finite
direct sums take unions, and direct summands cannot create support outside the
ambient support. Therefore every such generated support is even.

No K3 surface, Chow motive, Betti realization, or Hodge conjecture is defined
here. The geometric interpretation remains an explicit source interface.
-/

namespace Millennium.Hodge.K3MotiveParityFirewall

/-- A predicate on cohomological degrees. -/
abbrev DegreeSupport := ℕ → Prop

/-- Every supported degree is even. -/
def EvenSupported (A : DegreeSupport) : Prop :=
  ∀ n, A n → Even n

/-- Support of a tensor product: degrees add. -/
def tensorSupport (A B : DegreeSupport) : DegreeSupport :=
  fun n => ∃ i j, A i ∧ B j ∧ i + j = n

/-- Support of a finite direct sum: union of supports. -/
def sumSupport (A B : DegreeSupport) : DegreeSupport :=
  fun n => A n ∨ B n

/-- An integer Tate twist changes cohomological degree by an even amount. -/
def evenShiftSupport (k : ℕ) (A : DegreeSupport) : DegreeSupport :=
  fun n => ∃ i, A i ∧ i + 2 * k = n

/-- The degree support of one projective K3 surface. -/
def k3Support : DegreeSupport :=
  fun n => n = 0 ∨ n = 2 ∨ n = 4

/-- A toy support carrying the nonzero odd degree of an elliptic curve. -/
def ellipticSupport : DegreeSupport :=
  fun n => n = 0 ∨ n = 1 ∨ n = 2

/-- K3 cohomological support is even. -/
theorem k3_even_supported : EvenSupported k3Support := by
  intro n hn
  rcases hn with rfl | rfl | rfl
  · exact ⟨0, by norm_num⟩
  · exact ⟨1, by norm_num⟩
  · exact ⟨2, by norm_num⟩

/-- Tensor products preserve even support. -/
theorem tensor_even_supported
    {A B : DegreeSupport}
    (hA : EvenSupported A)
    (hB : EvenSupported B) :
    EvenSupported (tensorSupport A B) := by
  intro n hn
  rcases hn with ⟨i, j, hi, hj, rfl⟩
  rcases hA i hi with ⟨a, ha⟩
  rcases hB j hj with ⟨b, hb⟩
  refine ⟨a + b, ?_⟩
  omega

/-- Finite direct sums preserve even support. -/
theorem sum_even_supported
    {A B : DegreeSupport}
    (hA : EvenSupported A)
    (hB : EvenSupported B) :
    EvenSupported (sumSupport A B) := by
  intro n hn
  rcases hn with hn | hn
  · exact hA n hn
  · exact hB n hn

/-- Integer Tate shifts preserve degree parity. -/
theorem evenShift_even_supported
    {A : DegreeSupport}
    (hA : EvenSupported A)
    (k : ℕ) :
    EvenSupported (evenShiftSupport k A) := by
  intro n hn
  rcases hn with ⟨i, hi, rfl⟩
  rcases hA i hi with ⟨a, ha⟩
  refine ⟨a + k, ?_⟩
  omega

/-- A direct summand/support subset of an even-supported ambient object is even-supported. -/
theorem retract_even_supported
    {A B : DegreeSupport}
    (hsub : ∀ n, A n → B n)
    (hB : EvenSupported B) :
    EvenSupported A := by
  intro n hn
  exact hB n (hsub n hn)

/-- Degree one is present in the elliptic support. -/
theorem elliptic_degree_one : ellipticSupport 1 := by
  simp [ellipticSupport]

/-- The elliptic support is not even-supported. -/
theorem elliptic_not_even_supported : ¬ EvenSupported ellipticSupport := by
  intro h
  rcases h 1 elliptic_degree_one with ⟨k, hk⟩
  omega

/--
No support containing elliptic degree one can be a support subset of an
arbitrary even-supported K3/Tate tensor word.
-/
theorem no_elliptic_retract_of_even_supported
    {A : DegreeSupport}
    (hA : EvenSupported A) :
    ¬ (∀ n, ellipticSupport n → A n) := by
  intro hsub
  exact elliptic_not_even_supported (retract_even_supported hsub hA)

/-- One K3 self-tensor already remains even-supported. -/
theorem k3_self_tensor_even :
    EvenSupported (tensorSupport k3Support k3Support) :=
  tensor_even_supported k3_even_supported k3_even_supported

/-- Any finite displayed K3/Tate construction below remains even-supported. -/
theorem sample_generated_support_even (a b c : ℕ) :
    EvenSupported
      (sumSupport
        (evenShiftSupport a (tensorSupport k3Support k3Support))
        (evenShiftSupport b
          (tensorSupport k3Support
            (evenShiftSupport c k3Support)))) := by
  apply sum_even_supported
  · exact evenShift_even_supported k3_self_tensor_even a
  · apply evenShift_even_supported
    apply tensor_even_supported
    · exact k3_even_supported
    · exact evenShift_even_supported k3_even_supported c

/-- The sample K3/Tate support cannot contain the elliptic support as a retract. -/
theorem sample_generated_support_not_universal (a b c : ℕ) :
    ¬ (∀ n, ellipticSupport n →
      sumSupport
        (evenShiftSupport a (tensorSupport k3Support k3Support))
        (evenShiftSupport b
          (tensorSupport k3Support
            (evenShiftSupport c k3Support))) n) :=
  no_elliptic_retract_of_even_supported (sample_generated_support_even a b c)

#print axioms k3_even_supported
#print axioms tensor_even_supported
#print axioms sum_even_supported
#print axioms evenShift_even_supported
#print axioms retract_even_supported
#print axioms elliptic_not_even_supported
#print axioms no_elliptic_retract_of_even_supported
#print axioms sample_generated_support_even
#print axioms sample_generated_support_not_universal

end Millennium.Hodge.K3MotiveParityFirewall
