import Mathlib

/-!
# Faizal--Shabir FRD telescoping/adjoint firewall

Finite scalar algebra for a hostile audit of arXiv:2606.19362v1 Appendix C.

The source defines `T_{j+1} = T_j R_j` and then uses the displayed identity

`T_j (1 - R_j) T_j = T_j T_j - T_{j+1} T_{j+1}`.

That identity is false in general, even for real scalars.  The correct square
telescope is

`T_j^2 - (T_j R_j)^2 = T_j^2 (1 - R_j^2)`.

The file also records the scalar shadow of an adjoint-compatible resolvent
repair.  If `r = 1 - s a`, then

`1 - r^2 = a * (2 s - a s^2)`.

Thus the local positive defect naturally has the quadratic form
`2 s - a s^2`, not merely `s`, under the elementary contraction condition
`0 <= a*s <= 1`.

This file does not formalize the manuscript's operators, commutators,
finite-range decomposition, Yang--Mills theory, OS reconstruction, a mass gap,
or a Clay theorem.
-/

namespace Millennium.YangMills.FaizalShabirFRDTelescopingAdjointFirewall

/-- The Appendix-C displayed linear-defect to square-defect identity already
fails for `T = 1`, `R = 1/2`. -/
theorem c58_scalar_counterexample :
    let T : ℝ := 1
    let R : ℝ := 1 / 2
    T * (1 - R) * T ≠ T * T - (T * R) * (T * R) := by
  norm_num

/-- Exact difference between the claimed linear defect and the genuine square
telescope. -/
theorem linear_defect_missing_factor (T R : ℝ) :
    (T * T - (T * R) * (T * R)) - T * (1 - R) * T =
      T ^ 2 * R * (1 - R) := by
  ring

/-- The genuine scalar square-telescoping identity. -/
theorem square_telescoping_identity (T R : ℝ) :
    T * T - (T * R) * (T * R) = T ^ 2 * (1 - R ^ 2) := by
  ring

/-- Scalar shadow of the adjoint-compatible residual identity with
`r = 1 - s*a`: the square defect is generated by `2s - a s^2`. -/
theorem residual_square_defect_identity (a s : ℝ) :
    1 - (1 - s * a) ^ 2 = a * (2 * s - a * s ^ 2) := by
  ring

/-- Under the natural scalar contraction condition `0 <= a*s <= 1`, the
quadratic local defect `2s - a s^2` is nonnegative. -/
theorem residual_square_defect_nonnegative
    (a s : ℝ)
    (hs : 0 ≤ s)
    (hsa : a * s ≤ 1) :
    0 ≤ 2 * s - a * s ^ 2 := by
  have hfac : 2 * s - a * s ^ 2 = s * (2 - a * s) := by
    ring
  rw [hfac]
  exact mul_nonneg hs (by linarith)

/-- If the scalar residual is itself nonnegative and contractive, the genuine
square defect dominates the manuscript's linear defect by the exact missing
term `T^2 R (1-R)`. -/
theorem square_defect_dominates_linear_defect
    (T R : ℝ)
    (hR0 : 0 ≤ R)
    (hR1 : R ≤ 1) :
    T * (1 - R) * T ≤ T * T - (T * R) * (T * R) := by
  have hnonneg : 0 ≤ T ^ 2 * R * (1 - R) :=
    mul_nonneg (mul_nonneg (sq_nonneg T) hR0) (sub_nonneg.mpr hR1)
  have hdiff := linear_defect_missing_factor T R
  linarith

#print axioms c58_scalar_counterexample
#print axioms linear_defect_missing_factor
#print axioms square_telescoping_identity
#print axioms residual_square_defect_identity
#print axioms residual_square_defect_nonnegative
#print axioms square_defect_dominates_linear_defect

end Millennium.YangMills.FaizalShabirFRDTelescopingAdjointFirewall
